permalink: /:categories/:title 

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

pygments: true

production_url : http://trishdeitch.github.io

paginate: 5

paginate_file: index.html

timezone: America/New_York

markdown: kramdown
